server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.dejzcizymbhklddndqoh
spring.datasource.password=Kireti@2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# H2 console is disabled when using PostgreSQL
spring.h2.console.enabled=false

jwt.secret=MyJwtSecretKeyForKiranaBazar2026
jwt.expiration=86400000

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.test-connection=false
